{{- range $key, $svc := .Values.services | default dict }}
---
# the value of the dot : {{ . }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating-deep-dive.fullname" $ }}-svc-{{ $key }}
  labels:
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 4 }}
spec:
  selector:
    {{- include "templating-deep-dive.selectorLabels" $ | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ include "templating-deep-dive.validators.Port" $svc.port }}
      targetPort: {{ $.Values.containerPorts.http }}
  type: {{ $svc.type }}
{{- end }}