# custom name allow to set custom resource name
customName: 'my-custom-release'

# Replica count
# Image, both name and tag
# Service type and port

# replica count - number of replica count
replicaCount: 1

# Setting for nginx image
image:
  name: nginx
  tag: "1.27.0"

# nginx container port
containerPorts:
  http: 80

# Service list of type and exposed port
services:
  - type: ClusterIP
    port: 80