# custom name allow to set custom resource name
customName: 'my-custom-release'

# Replica count
# Image, both name and tag
# Service type and port

# replica count - number of replica count
replicaCount: 1

# Setting for nginx image
image:
  name: nginx
  tag: "1.27.0"

# security context run as user and fs group
securityContext:
  enabled: true
  runAsUser: 0
  fsGroup: 2000

# nginx container port
containerPorts:
  http: 80

# Service list of type and exposed port
services:
  svc1:
    type: ClusterIP
    port: 80
  scv2:
    type: NodePort
    port: 30007